name: Ubuntu2204 CI

on:
  push:
    paths-ignore:
      - ".devcontainer/**"
      - ".vscode/**"
      - "doc/**"
      - "*.md"
  pull_request:
    paths-ignore:
      - ".devcontainer/**"
      - ".vscode/**"
      - "doc/**"
      - "*.md"

jobs:
  gcc11-sve-build:
    name: GCC11-SVE build
    strategy:
      matrix:
        python-version: ["3.10.6"]
    runs-on: "ubuntu-22.04"
    env:
      C_COMPILER: "aarch64-linux-gnu-gcc-11"
      CXX_COMPILER: "aarch64-linux-gnu-g++-11"
      QULACS_OPT_FLAGS: "-march=armv8.2-a+sve"
      PYTHON: ${{ matrix.python-version }}
      QEMU_LD_PREFIX: "/usr/aarch64-linux-gnu"
      QEMU_CPU: "max,sve512=on"
    steps:
      - uses: actions/checkout@v2

      - name: Setup qemu
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build pkg-config libglib2.0-dev gcc-11-aarch64-linux-gnu g++-11-aarch64-linux-gnu
          wget https://download.qemu.org/qemu-7.1.0.tar.xz
          tar xJf qemu-7.1.0.tar.xz
          pushd qemu-7.1.0
          mkdir build; cd build
          ../configure --target-list=aarch64-linux-user
          make
          sudo make install

      - name: Install boost
        run: sudo apt-get install libboost-dev

      - name: Install qulacs for Ubuntu
        run: USE_TEST=Yes ./script/build_gcc.sh

      - name: Test in Ubuntu
        run: |
          cd ./build
          make buildtest
          qemu-aarch64 ../bin/csim_test
          qemu-aarch64 ../bin/cppsim_test
          qemu-aarch64 ../bin/vqcsim_test

