name: Ubuntu2204 CI

on:
  push:
    paths-ignore:
      - ".devcontainer/**"
      - ".vscode/**"
      - "doc/**"
      - "*.md"
  pull_request:
    paths-ignore:
      - ".devcontainer/**"
      - ".vscode/**"
      - "doc/**"
      - "*.md"

jobs:
  gcc11-sve-build:
    name: GCC11-SVE build
    strategy:
      matrix:
        python-version: ["3.10.6"]
    runs-on: "ubuntu-22.04"
    env:
      C_COMPILER: "aarch64-linux-gnu-gcc-11"
      CXX_COMPILER: "aarch64-linux-gnu-g++-11"
      QULACS_OPT_FLAGS: "-march=armv8.2-a+sve"
      PYTHON: ${{ matrix.python-version }}
      COVERAGE: "ON"
      QEMU_LD_PREFIX: "/usr/aarch64-linux-gnu"
      QEMU_CPU: "max,sve512=on"
    steps:
      - uses: actions/checkout@v2

      - name: Setup qemu
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build pkg-config libglib2.0-dev gcc-11-aarch64-linux-gnu g++-11-aarch64-linux-gnu
          wget https://download.qemu.org/qemu-7.1.0.tar.xz
          tar xJf qemu-7.1.0.tar.xz
          pushd qemu-7.1.0
          mkdir build; cd build
          ../configure --target-list=aarch64-linux-user
          make
          sudo make install

      - name: Install boost
        run: sudo apt-get install libboost-dev

      - name: Install LCOV
        run: |
          git clone -b v1.15 --depth 1 https://github.com/linux-test-project/lcov.git
          cd lcov
          sudo make install

      - name: Install qulacs for Ubuntu
        run: USE_TEST=Yes ./script/build_gcc.sh

      - name: Install qulacs Python module
        run: pip install .[ci]
      
      - name: Check stubs
        run: |
          ./script/update_stubs.sh
          diff=$(git diff)
          echo -n "$diff"
          # Without `-n`, `echo -n "$diff" | wc -l` is 1 even if `"$diff" is empty.`
          test $(echo -n "$diff" | wc -l) -eq 0

      - name: Test if stub is working
        run: |
          python python/stub-test/generate_mypy_tester.py qulacs
          mypy python/stub-test/names_qulacs.py

      - name: Test in Ubuntu
        run: |
          cd ./build
          make coverage
          make pythontest

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3

